<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class ProductUpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => 'required|max:255',
            'price' => 'required|integer|max:11',
            'sale_price' => 'integer|max:11|lt:price',
            'slug' => [
                'regex:/^[^<>]*$/',
                Rule::unique('products', 'slug')->ignore($this->id)
            ],
            'sku' => [
                'regex:/^[a-zA-Z0-9_.-]*$/',
                Rule::unique('products', 'sku')->ignore($this->id)
            ],
            'stocks' => 'required|integer|min:0',
            'supplier_id' => 'required|integer',
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
