<?php

namespace App\Models;

use App\Scopes\ClientScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

class Product extends Model
{
    protected $table = 'products';

    protected $hidden = ['created_at', 'updated_at', 'is_active'];

    protected $fillable = ['name', 'price', 'sale_price', 'feature_image', 'stocks', 'slug', 'sku', 'intro', 'desc', 'views', 'supplier', 'is_active', 'rate'];

    public function categories()
    {
        return $this->belongsToMany('App\Models\Category', 'relation_product_vs_category', 'product_id', 'category_id');
    }

    public function tags()
    {
        return $this->belongsToMany('App\Models\Tag', 'relation_product_vs_tag', 'product_id', 'tag_id');
    }

    public function comments()
    {
        return $this->hasMany('App\Models\Comment');
    }

    public function albums()
    {
        return $this->hasMany('App\Models\Album');
    }

    public function supplier()
    {
        return $this->belongsTo('App\Models\Supplier');
    }

    public function news()
    {
        return $this->hasOne('App\Models\News');
    }

    public function scopePopular($query)
    {
        return $query->orderByDesc('id');
    }

    /**
     * Scope a query to only include active users.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeActive($query)
    {
        return $query->where('is_active', '=', ACTIVE);
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope(new ClientScope);

        static::deleting(function ($product) {
            $product->news->delete();
        });
    }
}
